### ISSUE TITLE
Fileunzipping with Anaconda: remember to use forward slash "/" when defining the paths 

### ISSUE THREAD

**Issue by fmariottini** [pyElena21/FileManipulationTools#1]
In short, within Anaconda, I need to define the paths with forward slash "/" in order to be correctly interpreted by the module.

When using backslash "\" the module was doubling the slashes, no matter which os function I was using to define the paths before providing them to the module.

Just keep it in mind if you are also using Anaconda. : )

**Comment by pyElena21** [comment]
OK, thank you. Which error are you getting with Anaconda when using back slashes?

**Comment by pyElena21** [comment]
This however is not an issue with the code as no specific format is defined in the function, it is up to the user how they defined their path. Therefore i am closing this issue.
